version: '3.8'

services:
  discord-bot:
    build: .
    container_name: mqtt-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs  # Optional: for persistent logs